# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

# Alacritty now uses TOML formatting for its config files.
# This is a simple example.

# There are the specification here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# It is not obvious how it translates to TOML. But it is extremely straightforward.

# example: WINDOW, COLORS, etc. are tables, and should be represented as [window], [colors], respectively.
# specifics of variables go under them. e.g.- look under "dynamic_padding" under-
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#window
# write `dynamic_padding = true` (without backticks -`) under the table [window]
# for variables with multiple values, use "dotted keys". Like setting `padding.x = 5` under [window].
# This is simple. If not clear, do several trials and errors.

# Below is my initial set-up. The TOML homepage (https://toml.io/en/v1.0.0) was very helpful in figuring this out. 
# I put the file alacritty.toml in $HOME/.config/alacritty. However it can be kept anywhere among the places mentioned in
# https://github.com/alacritty/alacritty/tree/master#configuration

[window]
decorations = "None"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 0.9
padding.x = 10
padding.y = 10

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 12.0

# catppuccin-mocha colorscheme

[colors.primary]
background = '#1E1E2E' # base
foreground = '#CDD6F4' # text
# Bright and dim foreground colors
dim_foreground = '#CDD6F4' # text
bright_foreground = '#CDD6F4' # text

# Cursor colors
[colors.cursor]
text = '#1E1E2E' # base
cursor = '#F5E0DC' # rosewater

[colors.vi_mode_cursor]
text = '#1E1E2E' # base
cursor = '#B4BEFE' # lavender

# Search colors
[colors.search.matches]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

[colors.search.focused_match]
foreground = '#1E1E2E' # base
background = '#A6E3A1' # green

[colors.footer_bar]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

# Keyboard regex hints
[colors.hints.start]
foreground = '#1E1E2E' # base
background = '#F9E2AF' # yellow

[colors.hints.end]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

# Selection colors
[colors.selection]
text = '#1E1E2E' # base
background = '#F5E0DC' # rosewater

# Normal colors
[colors.normal]
black = '#45475A' # surface1
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1

# Bright colors
[colors.bright]
black = '#585B70' # surface2
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#A6ADC8' # subtext0

# Dim colors
[colors.dim]
black = '#45475A' # surface1
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1
