[window]

decorations = "None"
decorations_theme_variant = "None"
dimensions.columns = 128
dimensions.lines = 32
dynamic_padding = true
opacity = 0.90
padding = { x = 8, y = 8 }
position = "None"

[font]

normal.family = "JetBrainsMono Nerd Font Mono"
size = 13.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors.primary]

# Colors (Solarized Dark)

# Default colors
background = '#002b36'
foreground = '#839496'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#002b36'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'
