# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

# Alacritty now uses TOML formatting for its config files.
# This is a simple example.

# There are the specification here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# It is not obvious how it translates to TOML. But it is extremely straightforward.

# example: WINDOW, COLORS, etc. are tables, and should be represented as [window], [colors], respectively.
# specifics of variables go under them. e.g.- look under "dynamic_padding" under-
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#window
# write `dynamic_padding = true` (without backticks -`) under the table [window]
# for variables with multiple values, use "dotted keys". Like setting `padding.x = 5` under [window].
# This is simple. If not clear, do several trials and errors.

# Below is my initial set-up. The TOML homepage (https://toml.io/en/v1.0.0) was very helpful in figuring this out. 
# I put the file alacritty.toml in $HOME/.config/alacritty. However it can be kept anywhere among the places mentioned in
# https://github.com/alacritty/alacritty/tree/master#configuration

[window]
decorations = "None"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 0.9
padding.x = 10
padding.y = 10

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.0

# Nightfox Alacritty Colors
## name: terafox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/terafox/alacritty.toml

[colors.primary]
background = "#152528"
foreground = "#e6eaea"
dim_foreground = "#cbd9d8"
bright_foreground = "#eaeeee"

[colors.cursor]
text = "#e6eaea"
cursor = "#cbd9d8"

[colors.vi_mode_cursor]
text = "#e6eaea"
cursor = "#a1cdd8"

[colors.search.matches]
foreground = "#e6eaea"
background = "#425e5e"

[colors.search.focused_match]
foreground = "#e6eaea"
background = "#7aa4a1"

[colors.footer_bar]
foreground = "#e6eaea"
background = "#254147"

[colors.hints.start]
foreground = "#e6eaea"
background = "#ff8349"

[colors.hints.end]
foreground = "#e6eaea"
background = "#254147"

[colors.selection]
text = "#e6eaea"
background = "#293e40"

[colors.normal]
black = "#2f3239"
red = "#e85c51"
green = "#7aa4a1"
yellow = "#fda47f"
blue = "#5a93aa"
magenta = "#ad5c7c"
cyan = "#a1cdd8"
white = "#ebebeb"

[colors.bright]
black = "#4e5157"
red = "#eb746b"
green = "#8eb2af"
yellow = "#fdb292"
blue = "#73a3b7"
magenta = "#b97490"
cyan = "#afd4de"
white = "#eeeeee"

[colors.dim]
black = "#282a30"
red = "#c54e45"
green = "#688b89"
yellow = "#d78b6c"
blue = "#4d7d90"
magenta = "#934e69"
cyan = "#89aeb8"
white = "#c8c8c8"

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.
