set-option -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

set-option -g status-keys vi
set-window-option -g mode-keys vi

unbind-key e
bind-key -r e new-window 'nvim ~/.config/tmux/tmux.conf'

unbind-key r
bind-key -r r source-file "~/.config/tmux/tmux.conf" \; \
  display-message 'source-file done'

unbind-key '"'
bind-key | split-window -h -c '#{pane_current_path}'

unbind-key '%'
bind-key - split-window -v -c '#{pane_current_path}'

bind-key -r < swap-window -t -
bind-key -r > swap-window -t +

bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

set-option -g status-style bg=default,fg=default

set-option -g status-left-length 20
set-option -g status-right-length 60

set-option -g status-left '[#S] '
set-option -g status-right "[#{user}@#{host}][%a, %b %d][%R]"

set-window-option -g window-status-format '#I'
set-window-option -g window-status-current-format '#[bold]#I#[nobold]'

set-option -sg escape-time 10
set-option -g focus-events on
set-option -sa terminal-features ',foot:RGB'
