return {
  "tpope/vim-abolish",
  "tpope/vim-characterize",
  "tpope/vim-commentary",
  "tpope/vim-dadbod",
  "tpope/vim-fugitive",
  "tpope/vim-jdaddy",
  "tpope/vim-repeat",
  "tpope/vim-rhubarb",
  "tpope/vim-sensible",
  "tpope/vim-speeddating",
  "tpope/vim-surround",
  "tpope/vim-unimpaired",
  "tpope/vim-vinegar",
}
