let mapleader      = ' '
let maplocalleader = ','

let s:rc_files_dir = expand('~/.vim/rc')

let s:rc_files = [
      \  'caching',
      \  'globals',
      \  'options',
      \  'keymaps',
      \  'plugins',
      \  'autocmd',
      \  'guiopts',
      \]

for rc_file in s:rc_files
  let s:file = printf("%s/%s.vim", s:rc_files_dir, rc_file)
  execute printf("source %s", s:file)
endfor
