let mapleader      = "\<space>"
let maplocalleader = ","

" sourcery
let s:files = [
      \"options",
      \"globals",
      \"autocmd",
      \"plugins",
      \"keymaps",
      \"caching",
      \"guiopts"
      \]
let s:parent_dir = "~/.vim/rc/"

for file in s:files
  let s:f = s:parent_dir . file . '.vim'
  let s:c = 'source ' . s:f
  exe s:c
endfor
