local function kmap(m, k, v)
  vim.keymap.set(m, k, v, {noremap = true})
end

kmap('i', 'jj', '<Esc>')

kmap('n', '<Leader>;', ':')

-- edit/source neovim config files
kmap('n', '<Leader>erc', ':e ~/.config/nvim/init.lua<CR>')

kmap('n', '<Leader>eop', ':e ~/.config/nvim/lua/options.lua<CR>')
kmap('n', '<Leader>ekm', ':e ~/.config/nvim/lua/keymaps.lua<CR>')
kmap('n', '<Leader>epg', ':e ~/.config/nvim/lua/plugins/<CR>')

kmap('n', '<Leader>src', ':so ~/.config/nvim/init.lua<CR>')

kmap('n', '<Leader>sop', ':so ~/.config/nvim/lua/options.lua<CR>')
kmap('n', '<Leader>skm', ':so ~/.config/nvim/lua/keymaps.lua<CR>')

-- file commands
kmap('n', '<Leader>fw', ':w<CR>')
kmap('n', '<Leader>fq', ':q<CR>')

-- window navigation
kmap('n', '<C-h>', '<C-w>h')
kmap('n', '<C-j>', '<C-w>j')
kmap('n', '<C-k>', '<C-w>k')
kmap('n', '<C-l>', '<C-w>l')

-- latex bindings
kmap('i', '<Leader>pna', '^{-a}')
kmap('i', '<Leader>pnb', '^{-b}')
kmap('i', '<Leader>pnc', '^{-c}')
kmap('i', '<Leader>pnd', '^{-d}')
kmap('i', '<Leader>pne', '^{-e}')
kmap('i', '<Leader>pnf', '^{-f}')
kmap('i', '<Leader>png', '^{-g}')
kmap('i', '<Leader>pnh', '^{-h}')
kmap('i', '<Leader>pni', '^{-i}')
kmap('i', '<Leader>pnj', '^{-j}')
kmap('i', '<Leader>pnk', '^{-k}')
kmap('i', '<Leader>pnl', '^{-l}')
kmap('i', '<Leader>pnm', '^{-m}')
kmap('i', '<Leader>pnn', '^{-n}')
kmap('i', '<Leader>pno', '^{-o}')
kmap('i', '<Leader>pnp', '^{-p}')
kmap('i', '<Leader>pnq', '^{-q}')
kmap('i', '<Leader>pnr', '^{-r}')
kmap('i', '<Leader>pns', '^{-s}')
kmap('i', '<Leader>pnt', '^{-t}')
kmap('i', '<Leader>pnu', '^{-u}')
kmap('i', '<Leader>pnv', '^{-v}')
kmap('i', '<Leader>pnw', '^{-w}')
kmap('i', '<Leader>pnx', '^{-x}')
kmap('i', '<Leader>pny', '^{-y}')
kmap('i', '<Leader>pnz', '^{-z}')

kmap('i', '<Leader>ppa', '^{a}')
kmap('i', '<Leader>ppb', '^{b}')
kmap('i', '<Leader>ppc', '^{c}')
kmap('i', '<Leader>ppd', '^{d}')
kmap('i', '<Leader>ppe', '^{e}')
kmap('i', '<Leader>ppf', '^{f}')
kmap('i', '<Leader>ppg', '^{g}')
kmap('i', '<Leader>pph', '^{h}')
kmap('i', '<Leader>ppi', '^{i}')
kmap('i', '<Leader>ppj', '^{j}')
kmap('i', '<Leader>ppk', '^{k}')
kmap('i', '<Leader>ppl', '^{l}')
kmap('i', '<Leader>ppm', '^{m}')
kmap('i', '<Leader>ppn', '^{n}')
kmap('i', '<Leader>ppo', '^{o}')
kmap('i', '<Leader>ppp', '^{p}')
kmap('i', '<Leader>ppq', '^{q}')
kmap('i', '<Leader>ppr', '^{r}')
kmap('i', '<Leader>pps', '^{s}')
kmap('i', '<Leader>ppt', '^{t}')
kmap('i', '<Leader>ppu', '^{u}')
kmap('i', '<Leader>ppv', '^{v}')
kmap('i', '<Leader>ppw', '^{w}')
kmap('i', '<Leader>ppx', '^{x}')
kmap('i', '<Leader>ppy', '^{y}')
kmap('i', '<Leader>ppz', '^{z}')

kmap('i', '<Leader>bna', '_{-a}')
kmap('i', '<Leader>bnb', '_{-b}')
kmap('i', '<Leader>bnc', '_{-c}')
kmap('i', '<Leader>bnd', '_{-d}')
kmap('i', '<Leader>bne', '_{-e}')
kmap('i', '<Leader>bnf', '_{-f}')
kmap('i', '<Leader>bng', '_{-g}')
kmap('i', '<Leader>bnh', '_{-h}')
kmap('i', '<Leader>bni', '_{-i}')
kmap('i', '<Leader>bnj', '_{-j}')
kmap('i', '<Leader>bnk', '_{-k}')
kmap('i', '<Leader>bnl', '_{-l}')
kmap('i', '<Leader>bnm', '_{-m}')
kmap('i', '<Leader>bnn', '_{-n}')
kmap('i', '<Leader>bno', '_{-o}')
kmap('i', '<Leader>bnp', '_{-p}')
kmap('i', '<Leader>bnq', '_{-q}')
kmap('i', '<Leader>bnr', '_{-r}')
kmap('i', '<Leader>bns', '_{-s}')
kmap('i', '<Leader>bnt', '_{-t}')
kmap('i', '<Leader>bnu', '_{-u}')
kmap('i', '<Leader>bnv', '_{-v}')
kmap('i', '<Leader>bnw', '_{-w}')
kmap('i', '<Leader>bnx', '_{-x}')
kmap('i', '<Leader>bny', '_{-y}')
kmap('i', '<Leader>bnz', '_{-z}')

kmap('i', '<Leader>bpa', '_{a}')
kmap('i', '<Leader>bpb', '_{b}')
kmap('i', '<Leader>bpc', '_{c}')
kmap('i', '<Leader>bpd', '_{d}')
kmap('i', '<Leader>bpe', '_{e}')
kmap('i', '<Leader>bpf', '_{f}')
kmap('i', '<Leader>bpg', '_{g}')
kmap('i', '<Leader>bph', '_{h}')
kmap('i', '<Leader>bpi', '_{i}')
kmap('i', '<Leader>bpj', '_{j}')
kmap('i', '<Leader>bpk', '_{k}')
kmap('i', '<Leader>bpl', '_{l}')
kmap('i', '<Leader>bpm', '_{m}')
kmap('i', '<Leader>bpn', '_{n}')
kmap('i', '<Leader>bpo', '_{o}')
kmap('i', '<Leader>bpp', '_{p}')
kmap('i', '<Leader>bpq', '_{q}')
kmap('i', '<Leader>bpr', '_{r}')
kmap('i', '<Leader>bps', '_{s}')
kmap('i', '<Leader>bpt', '_{t}')
kmap('i', '<Leader>bpu', '_{u}')
kmap('i', '<Leader>bpv', '_{v}')
kmap('i', '<Leader>bpw', '_{w}')
kmap('i', '<Leader>bpx', '_{x}')
kmap('i', '<Leader>bpy', '_{y}')
kmap('i', '<Leader>bpz', '_{z}')

kmap('i', '<Leader>pn9', '^{-9}')
kmap('i', '<Leader>pn8', '^{-8}')
kmap('i', '<Leader>pn7', '^{-7}')
kmap('i', '<Leader>pn6', '^{-6}')
kmap('i', '<Leader>pn5', '^{-5}')
kmap('i', '<Leader>pn4', '^{-4}')
kmap('i', '<Leader>pn3', '^{-3}')
kmap('i', '<Leader>pn2', '^{-2}')
kmap('i', '<Leader>pn1', '^{-1}')

kmap('i', '<Leader>pp0', '^{0}')
kmap('i', '<Leader>pp1', '^{1}')
kmap('i', '<Leader>pp2', '^{2}')
kmap('i', '<Leader>pp3', '^{3}')
kmap('i', '<Leader>pp4', '^{4}')
kmap('i', '<Leader>pp5', '^{5}')
kmap('i', '<Leader>pp6', '^{6}')
kmap('i', '<Leader>pp7', '^{7}')
kmap('i', '<Leader>pp8', '^{8}')
kmap('i', '<Leader>pp9', '^{9}')

kmap('i', '<Leader>bn9', '_{-9}')
kmap('i', '<Leader>bn8', '_{-8}')
kmap('i', '<Leader>bn7', '_{-7}')
kmap('i', '<Leader>bn6', '_{-6}')
kmap('i', '<Leader>bn5', '_{-5}')
kmap('i', '<Leader>bn4', '_{-4}')
kmap('i', '<Leader>bn3', '_{-3}')
kmap('i', '<Leader>bn2', '_{-2}')
kmap('i', '<Leader>bn1', '_{-1}')

kmap('i', '<Leader>bp0', '_{0}')
kmap('i', '<Leader>bp1', '_{1}')
kmap('i', '<Leader>bp2', '_{2}')
kmap('i', '<Leader>bp3', '_{3}')
kmap('i', '<Leader>bp4', '_{4}')
kmap('i', '<Leader>bp5', '_{5}')
kmap('i', '<Leader>bp6', '_{6}')
kmap('i', '<Leader>bp7', '_{7}')
kmap('i', '<Leader>bp8', '_{8}')
kmap('i', '<Leader>bp9', '_{9}')

kmap('i', '<Leader>mbba', '\\mathbb{A}')
kmap('i', '<Leader>mbbb', '\\mathbb{B}')
kmap('i', '<Leader>mbbc', '\\mathbb{C}')
kmap('i', '<Leader>mbbd', '\\mathbb{D}')
kmap('i', '<Leader>mbbe', '\\mathbb{E}')
kmap('i', '<Leader>mbbf', '\\mathbb{F}')
kmap('i', '<Leader>mbbg', '\\mathbb{G}')
kmap('i', '<Leader>mbbh', '\\mathbb{H}')
kmap('i', '<Leader>mbbi', '\\mathbb{I}')
kmap('i', '<Leader>mbbj', '\\mathbb{J}')
kmap('i', '<Leader>mbbk', '\\mathbb{K}')
kmap('i', '<Leader>mbbl', '\\mathbb{L}')
kmap('i', '<Leader>mbbm', '\\mathbb{M}')
kmap('i', '<Leader>mbbn', '\\mathbb{N}')
kmap('i', '<Leader>mbbo', '\\mathbb{O}')
kmap('i', '<Leader>mbbp', '\\mathbb{P}')
kmap('i', '<Leader>mbbq', '\\mathbb{Q}')
kmap('i', '<Leader>mbbr', '\\mathbb{R}')
kmap('i', '<Leader>mbbs', '\\mathbb{S}')
kmap('i', '<Leader>mbbt', '\\mathbb{T}')
kmap('i', '<Leader>mbbu', '\\mathbb{U}')
kmap('i', '<Leader>mbbv', '\\mathbb{V}')
kmap('i', '<Leader>mbbw', '\\mathbb{W}')
kmap('i', '<Leader>mbbx', '\\mathbb{X}')
kmap('i', '<Leader>mbby', '\\mathbb{Y}')
kmap('i', '<Leader>mbbz', '\\mathbb{Z}')

kmap('i', '<Leader>pkg', '\\usepackage{<++>}<Esc>ci{')
kmap('i', '<Leader>ttl', '\\title{An Awesome Title}\n')
kmap('i', '<Leader>aut', '\\author{Marcelo Bezerra}\n')
kmap('i', '<Leader>dat', '\\date{\\today}')

kmap('i', '<Leader>leq', '\\label{eq:<++>}\n<++><Esc>#ca<')

kmap('i', '<Leader>cor', '\\begin{corollary}\n<++>\n\\end{corollary}\n<++><Esc>#S')
kmap('i', '<Leader>def', '\\begin{definition}\n<++>\n\\end{definition}\n<++><Esc>#S')
kmap('i', '<Leader>exm', '\\begin{example}\n<++>\n\\end{example}\n<++><Esc>#S')
kmap('i', '<Leader>lmm', '\\begin{lemma}\n<++>\n\\end{lemma}\n<++><Esc>#S')
kmap('i', '<Leader>rmk', '\\begin{remark}\n<++>\n\\end{remark}\n<++><Esc>#S')
kmap('i', '<Leader>thm', '\\begin{theorem}\n<++>\n\\end{theorem}\n<++><Esc>#S')
