local kmap = vim.keymap.set
local opts = { noremap = true }

kmap('i', 'jj', '<Esc>', opts)

kmap('n', '<Leader>;', ':', opts)

-- edit/source neovim config files
kmap('n', '<Leader>erc', ':edit $MYVIMRC<CR>', opts)

kmap('n', '<Leader>eop', ':edit ~/.config/nvim/lua/options.lua<CR>', opts)
kmap('n', '<Leader>ekm', ':edit ~/.config/nvim/lua/keymaps.lua<CR>', opts)
kmap('n', '<Leader>epg', ':edit ~/.config/nvim/lua/plugins.lua<CR>', opts)

kmap('n', '<Leader>src', ':source $MYVIMRC<CR>', opts)

kmap('n', '<Leader>sop', ':source ~/.config/nvim/lua/options.lua<CR>', opts)
kmap('n', '<Leader>skm', ':source ~/.config/nvim/lua/keymaps.lua<CR>', opts)
kmap('n', '<Leader>spg', ':source ~/.config/nvim/lua/plugins.lua<CR>', opts)

-- file commands
kmap('n', '<Leader>fw', ':w<CR>', opts)
kmap('n', '<Leader>fq', ':q<CR>', opts)

-- window navigation
kmap('n', '<C-h>', '<C-w>h', opts)
kmap('n', '<C-j>', '<C-w>j', opts)
kmap('n', '<C-k>', '<C-w>k', opts)
kmap('n', '<C-l>', '<C-w>l', opts)

-- latex bindings
kmap('i', '<Leader>pna', '^{-a}', opts)
kmap('i', '<Leader>pnb', '^{-b}', opts)
kmap('i', '<Leader>pnc', '^{-c}', opts)
kmap('i', '<Leader>pnd', '^{-d}', opts)
kmap('i', '<Leader>pne', '^{-e}', opts)
kmap('i', '<Leader>pnf', '^{-f}', opts)
kmap('i', '<Leader>png', '^{-g}', opts)
kmap('i', '<Leader>pnh', '^{-h}', opts)
kmap('i', '<Leader>pni', '^{-i}', opts)
kmap('i', '<Leader>pnj', '^{-j}', opts)
kmap('i', '<Leader>pnk', '^{-k}', opts)
kmap('i', '<Leader>pnl', '^{-l}', opts)
kmap('i', '<Leader>pnm', '^{-m}', opts)
kmap('i', '<Leader>pnn', '^{-n}', opts)
kmap('i', '<Leader>pno', '^{-o}', opts)
kmap('i', '<Leader>pnp', '^{-p}', opts)
kmap('i', '<Leader>pnq', '^{-q}', opts)
kmap('i', '<Leader>pnr', '^{-r}', opts)
kmap('i', '<Leader>pns', '^{-s}', opts)
kmap('i', '<Leader>pnt', '^{-t}', opts)
kmap('i', '<Leader>pnu', '^{-u}', opts)
kmap('i', '<Leader>pnv', '^{-v}', opts)
kmap('i', '<Leader>pnw', '^{-w}', opts)
kmap('i', '<Leader>pnx', '^{-x}', opts)
kmap('i', '<Leader>pny', '^{-y}', opts)
kmap('i', '<Leader>pnz', '^{-z}', opts)

kmap('i', '<Leader>ppa', '^{a}', opts)
kmap('i', '<Leader>ppb', '^{b}', opts)
kmap('i', '<Leader>ppc', '^{c}', opts)
kmap('i', '<Leader>ppd', '^{d}', opts)
kmap('i', '<Leader>ppe', '^{e}', opts)
kmap('i', '<Leader>ppf', '^{f}', opts)
kmap('i', '<Leader>ppg', '^{g}', opts)
kmap('i', '<Leader>pph', '^{h}', opts)
kmap('i', '<Leader>ppi', '^{i}', opts)
kmap('i', '<Leader>ppj', '^{j}', opts)
kmap('i', '<Leader>ppk', '^{k}', opts)
kmap('i', '<Leader>ppl', '^{l}', opts)
kmap('i', '<Leader>ppm', '^{m}', opts)
kmap('i', '<Leader>ppn', '^{n}', opts)
kmap('i', '<Leader>ppo', '^{o}', opts)
kmap('i', '<Leader>ppp', '^{p}', opts)
kmap('i', '<Leader>ppq', '^{q}', opts)
kmap('i', '<Leader>ppr', '^{r}', opts)
kmap('i', '<Leader>pps', '^{s}', opts)
kmap('i', '<Leader>ppt', '^{t}', opts)
kmap('i', '<Leader>ppu', '^{u}', opts)
kmap('i', '<Leader>ppv', '^{v}', opts)
kmap('i', '<Leader>ppw', '^{w}', opts)
kmap('i', '<Leader>ppx', '^{x}', opts)
kmap('i', '<Leader>ppy', '^{y}', opts)
kmap('i', '<Leader>ppz', '^{z}', opts)

kmap('i', '<Leader>bna', '_{-a}', opts)
kmap('i', '<Leader>bnb', '_{-b}', opts)
kmap('i', '<Leader>bnc', '_{-c}', opts)
kmap('i', '<Leader>bnd', '_{-d}', opts)
kmap('i', '<Leader>bne', '_{-e}', opts)
kmap('i', '<Leader>bnf', '_{-f}', opts)
kmap('i', '<Leader>bng', '_{-g}', opts)
kmap('i', '<Leader>bnh', '_{-h}', opts)
kmap('i', '<Leader>bni', '_{-i}', opts)
kmap('i', '<Leader>bnj', '_{-j}', opts)
kmap('i', '<Leader>bnk', '_{-k}', opts)
kmap('i', '<Leader>bnl', '_{-l}', opts)
kmap('i', '<Leader>bnm', '_{-m}', opts)
kmap('i', '<Leader>bnn', '_{-n}', opts)
kmap('i', '<Leader>bno', '_{-o}', opts)
kmap('i', '<Leader>bnp', '_{-p}', opts)
kmap('i', '<Leader>bnq', '_{-q}', opts)
kmap('i', '<Leader>bnr', '_{-r}', opts)
kmap('i', '<Leader>bns', '_{-s}', opts)
kmap('i', '<Leader>bnt', '_{-t}', opts)
kmap('i', '<Leader>bnu', '_{-u}', opts)
kmap('i', '<Leader>bnv', '_{-v}', opts)
kmap('i', '<Leader>bnw', '_{-w}', opts)
kmap('i', '<Leader>bnx', '_{-x}', opts)
kmap('i', '<Leader>bny', '_{-y}', opts)
kmap('i', '<Leader>bnz', '_{-z}', opts)

kmap('i', '<Leader>bpa', '_{a}', opts)
kmap('i', '<Leader>bpb', '_{b}', opts)
kmap('i', '<Leader>bpc', '_{c}', opts)
kmap('i', '<Leader>bpd', '_{d}', opts)
kmap('i', '<Leader>bpe', '_{e}', opts)
kmap('i', '<Leader>bpf', '_{f}', opts)
kmap('i', '<Leader>bpg', '_{g}', opts)
kmap('i', '<Leader>bph', '_{h}', opts)
kmap('i', '<Leader>bpi', '_{i}', opts)
kmap('i', '<Leader>bpj', '_{j}', opts)
kmap('i', '<Leader>bpk', '_{k}', opts)
kmap('i', '<Leader>bpl', '_{l}', opts)
kmap('i', '<Leader>bpm', '_{m}', opts)
kmap('i', '<Leader>bpn', '_{n}', opts)
kmap('i', '<Leader>bpo', '_{o}', opts)
kmap('i', '<Leader>bpp', '_{p}', opts)
kmap('i', '<Leader>bpq', '_{q}', opts)
kmap('i', '<Leader>bpr', '_{r}', opts)
kmap('i', '<Leader>bps', '_{s}', opts)
kmap('i', '<Leader>bpt', '_{t}', opts)
kmap('i', '<Leader>bpu', '_{u}', opts)
kmap('i', '<Leader>bpv', '_{v}', opts)
kmap('i', '<Leader>bpw', '_{w}', opts)
kmap('i', '<Leader>bpx', '_{x}', opts)
kmap('i', '<Leader>bpy', '_{y}', opts)
kmap('i', '<Leader>bpz', '_{z}', opts)

kmap('i', '<Leader>pn9', '^{-9}', opts)
kmap('i', '<Leader>pn8', '^{-8}', opts)
kmap('i', '<Leader>pn7', '^{-7}', opts)
kmap('i', '<Leader>pn6', '^{-6}', opts)
kmap('i', '<Leader>pn5', '^{-5}', opts)
kmap('i', '<Leader>pn4', '^{-4}', opts)
kmap('i', '<Leader>pn3', '^{-3}', opts)
kmap('i', '<Leader>pn2', '^{-2}', opts)
kmap('i', '<Leader>pn1', '^{-1}', opts)

kmap('i', '<Leader>pp0', '^{0}', opts)
kmap('i', '<Leader>pp1', '^{1}', opts)
kmap('i', '<Leader>pp2', '^{2}', opts)
kmap('i', '<Leader>pp3', '^{3}', opts)
kmap('i', '<Leader>pp4', '^{4}', opts)
kmap('i', '<Leader>pp5', '^{5}', opts)
kmap('i', '<Leader>pp6', '^{6}', opts)
kmap('i', '<Leader>pp7', '^{7}', opts)
kmap('i', '<Leader>pp8', '^{8}', opts)
kmap('i', '<Leader>pp9', '^{9}', opts)

kmap('i', '<Leader>bn9', '_{-9}', opts)
kmap('i', '<Leader>bn8', '_{-8}', opts)
kmap('i', '<Leader>bn7', '_{-7}', opts)
kmap('i', '<Leader>bn6', '_{-6}', opts)
kmap('i', '<Leader>bn5', '_{-5}', opts)
kmap('i', '<Leader>bn4', '_{-4}', opts)
kmap('i', '<Leader>bn3', '_{-3}', opts)
kmap('i', '<Leader>bn2', '_{-2}', opts)
kmap('i', '<Leader>bn1', '_{-1}', opts)

kmap('i', '<Leader>bp0', '_{0}', opts)
kmap('i', '<Leader>bp1', '_{1}', opts)
kmap('i', '<Leader>bp2', '_{2}', opts)
kmap('i', '<Leader>bp3', '_{3}', opts)
kmap('i', '<Leader>bp4', '_{4}', opts)
kmap('i', '<Leader>bp5', '_{5}', opts)
kmap('i', '<Leader>bp6', '_{6}', opts)
kmap('i', '<Leader>bp7', '_{7}', opts)
kmap('i', '<Leader>bp8', '_{8}', opts)
kmap('i', '<Leader>bp9', '_{9}', opts)

kmap('i', '<Leader>mbba', '\\mathbb{A}', opts)
kmap('i', '<Leader>mbbb', '\\mathbb{B}', opts)
kmap('i', '<Leader>mbbc', '\\mathbb{C}', opts)
kmap('i', '<Leader>mbbd', '\\mathbb{D}', opts)
kmap('i', '<Leader>mbbe', '\\mathbb{E}', opts)
kmap('i', '<Leader>mbbf', '\\mathbb{F}', opts)
kmap('i', '<Leader>mbbg', '\\mathbb{G}', opts)
kmap('i', '<Leader>mbbh', '\\mathbb{H}', opts)
kmap('i', '<Leader>mbbi', '\\mathbb{I}', opts)
kmap('i', '<Leader>mbbj', '\\mathbb{J}', opts)
kmap('i', '<Leader>mbbk', '\\mathbb{K}', opts)
kmap('i', '<Leader>mbbl', '\\mathbb{L}', opts)
kmap('i', '<Leader>mbbm', '\\mathbb{M}', opts)
kmap('i', '<Leader>mbbn', '\\mathbb{N}', opts)
kmap('i', '<Leader>mbbo', '\\mathbb{O}', opts)
kmap('i', '<Leader>mbbp', '\\mathbb{P}', opts)
kmap('i', '<Leader>mbbq', '\\mathbb{Q}', opts)
kmap('i', '<Leader>mbbr', '\\mathbb{R}', opts)
kmap('i', '<Leader>mbbs', '\\mathbb{S}', opts)
kmap('i', '<Leader>mbbt', '\\mathbb{T}', opts)
kmap('i', '<Leader>mbbu', '\\mathbb{U}', opts)
kmap('i', '<Leader>mbbv', '\\mathbb{V}', opts)
kmap('i', '<Leader>mbbw', '\\mathbb{W}', opts)
kmap('i', '<Leader>mbbx', '\\mathbb{X}', opts)
kmap('i', '<Leader>mbby', '\\mathbb{Y}', opts)
kmap('i', '<Leader>mbbz', '\\mathbb{Z}', opts)

kmap('i', '<Leader>pkg', '\\usepackage{<++>}<Esc>ci{', opts)
kmap('i', '<Leader>ttl', '\\title{An Awesome Title}\n', opts)
kmap('i', '<Leader>aut', '\\author{Marcelo Bezerra}\n', opts)
kmap('i', '<Leader>dat', '\\date{\\today}', opts)

kmap('i', '<Leader>leq', '\\label{eq:<++>}\n<++><Esc>#ca<', opts)

kmap('i', '<Leader>equ', '\\begin{equation}\n<++>\n\\end{equation}\n<++><Esc>#S', opts)
kmap('i', '<Leader>cor', '\\begin{corollary}\n<++>\n\\end{corollary}\n<++><Esc>#S', opts)
kmap('i', '<Leader>def', '\\begin{definition}\n<++>\n\\end{definition}\n<++><Esc>#S', opts)
kmap('i', '<Leader>lmm', '\\begin{lemma}\n<++>\n\\end{lemma}\n<++><Esc>#S', opts)
kmap('i', '<Leader>rmk', '\\begin{remark}\n<++>\n\\end{remark}\n<++><Esc>#S', opts)
kmap('i', '<Leader>thm', '\\begin{theorem}\n<++>\n\\end{theorem}\n<++><Esc>#S', opts)
