set-option -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

setw -g mode-keys vi

set -g status-right "(#h) %a, %b %d %R"

set -g status-bg color235
set -g status-fg color243

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H resize-pane -L 8
bind -r J resize-pane -D 8
bind -r K resize-pane -U 8
bind -r L resize-pane -R 8

bind R source-file ~/.config/tmux/tmux.conf \; \
  display-message "source-file done"
