set-option -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

set -g default-terminal 'tmux-256color'

set -g editor vi

setw -g mode-keys vi

set -g status-right "(arch) %a, %b %d %Y %R"

# set -g status-bg color235
# set -g status-fg color245

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind R source-file ~/.config/tmux/tmux.conf \; \
  display-message "source-file done"
